# Generated by Django 3.0.4 on 2020-03-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
