# Generated by Django 3.0.3 on 2020-03-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
